(() => {
  const view = () => document.getElementById('phoneView');
  const history = [];
  let current = 'androidhome';
  const logo = 'assets/azcare-logo-white.svg';

  const app = (icon, label, target) => `<button class="android-app" data-az-app="${target}"><span>${target === 'protect' ? `<img class="az-app-logo" src="${logo}" alt="A-Z Care">` : icon}</span><small>${label}</small></button>`;
  const subhead = (label, title) => `<div class="phone-subhead"><button data-az-back aria-label="Back">‹</button><div><small>${label}</small><h3>${title}</h3></div></div>`;
  const toggle = (title, note) => `<div class="settings-toggle-row"><div><strong>${title}</strong><small>${note}</small></div><button class="settings-toggle on" data-setting-toggle></button></div>`;

  function tick() {
    const clock = document.getElementById('azClock');
    if (clock) clock.textContent = new Intl.DateTimeFormat(undefined, {hour:'2-digit', minute:'2-digit'}).format(new Date());
    const greeting = document.getElementById('azGreeting');
    const date = document.getElementById('azDate');
    const now = new Date();
    if (greeting) greeting.textContent = now.getHours() < 12 ? 'GOOD MORNING' : now.getHours() < 17 ? 'GOOD AFTERNOON' : now.getHours() < 22 ? 'GOOD EVENING' : 'GOOD NIGHT';
    if (date) date.textContent = new Intl.DateTimeFormat(undefined, {weekday:'long', day:'numeric', month:'long'}).format(now);
  }

  function home() {
    const p = view(); if (!p) return;
    current = 'androidhome'; history.length = 0;
    p.innerHTML = `<div class="android-status"><b id="azClock"></b><span>5G&nbsp;&nbsp;⌁&nbsp;&nbsp;82%</span></div><div class="android-greeting"><small id="azGreeting"></small><h3>Alex</h3><p id="azDate"></p></div><button class="android-protect-widget" data-az-app="protect"><span class="shield-dot"><img class="az-widget-logo" src="${logo}" alt="A-Z Care"></span><span><strong>You're protected</strong><small>No threats detected</small></span><b>›</b></button><div class="android-grid">${app('◇','Protect','protect')}${app('✦','AI Care','ai')}${app('♥','Health','health')}${app('♙','Family','familydetail')}${app('⌖','Location','location')}${app('👤','Contacts','contacts')}${app('⚙','Settings','settings')}${app('SOS','SOS','sosphone')}</div><div class="android-dock">${app('☎','Phone','calls')}${app('✉','Messages','messages')}${app('','Browser','browser')}${app('','Camera','camera')}</div><div class="android-gesture" data-az-home></div>`;
    bind(); tick();
  }

  const screens = {
    protect: () => `${subhead('PROTECTION','Safety Center')}<div class="status-card"><div class="shield">✓</div><div><strong>Protection ready</strong><small>Demo safety services active</small></div></div><div class="phone-label">CHECK SOMETHING</div><div class="phone-app-grid compact"><button data-az-app="messages"><span>✉</span><strong>Message</strong></button><button data-az-app="browser"><span>↗</span><strong>Link</strong></button><button data-az-app="calls"><span>☎</span><strong>Caller</strong></button><button data-az-app="ai"><span>✦</span><strong>Ask AI</strong></button></div><div class="phone-label">RECENT</div><button class="phone-alert-row" data-az-app="messages"><span>⚠</span><div><strong>Suspicious message</strong><small>Potential phishing link · 12:14</small></div><b>›</b></button>`,
    ai: () => `${subhead('SAFETY ASSISTANT','A-Z Care AI')}<div class="ai-phone-chat">“My bank says I need to verify my account through a link. Is this safe?”</div><div class="ai-phone-result"><strong>⚠ Pause before acting</strong><p>Unexpected urgency and a login link are common scam signals. Open your bank app directly or call the official number instead.</p></div><div class="phone-label">ASK A-Z CARE</div><div class="phone-app-grid compact"><button data-az-app="messages"><span>✉</span><strong>Message</strong></button><button data-az-app="browser"><span>↗</span><strong>Link</strong></button><button data-az-app="calls"><span>☎</span><strong>Call</strong></button><button data-az-app="contacts"><span>♥</span><strong>Ask family</strong></button></div>`,
    calls: () => `${subhead('CALL PROTECTION','Incoming call')}<div class="caller-big">?</div><h4 class="phone-center-title">Unknown caller</h4><p class="phone-center-muted">+371 2X XXX XXX</p><div class="phone-warning"><strong>⚠ Possible scam</strong><p>This caller may be impersonating an organization. Never share passwords or verification codes.</p></div><div class="phone-action-row"><button class="good">Decline</button><button data-az-app="ai">✦ Ask AI</button></div><button class="phone-wide-action" data-az-app="contacts">Call trusted contact instead</button>`,
    messages: () => `${subhead('SAFE INBOX','Message check')}<div class="sms-phone-bubble">Your bank account has been blocked. Verify now: <b>secure-bank-check.example</b></div><div class="phone-warning"><strong>⚠ Be careful</strong><p>A-Z Care noticed urgency, an unfamiliar link and a request to take account action.</p></div><div class="phone-signal-list"><span>• Creates urgency</span><span>• Unknown domain</span><span>• Account threat</span></div><div class="phone-action-row"><button>Delete</button><button data-az-app="ai">✦ Ask AI</button></div><button class="phone-wide-action" data-az-app="contacts">Ask family</button>`,
    contacts: () => `${subhead('TRUSTED PEOPLE','My contacts')}<div class="trusted-list"><div><span class="mini-avatar">A</span><p><strong>Anna</strong><small>Daughter · Trusted</small></p><button>☎</button></div><div><span class="mini-avatar">M</span><p><strong>Michael</strong><small>Son · Trusted</small></p><button>☎</button></div><div><span class="mini-avatar">N</span><p><strong>Neighbour</strong><small>Trusted helper</small></p><button>☎</button></div></div><button class="phone-wide-action">+ Add trusted person</button>`,
    location: () => `${subhead('FAMILY','Family Hub')}<div class="mini-map"><span class="map-pin a">A</span><span class="map-pin m">M</span></div><div class="phone-label">FAMILY STATUS</div><button class="family-mini phone-row-button" data-az-app="familydetail"><div class="mini-avatar">M</div><div><strong>Mom · Home</strong><small>Battery 74% · Online</small></div><span class="dot"></span></button><button class="family-mini phone-row-button" data-az-app="battery"><div class="mini-avatar">G</div><div><strong>Grandma · Home</strong><small>Battery 12% · Low</small></div><span class="warn-dot"></span></button><div class="phone-mini-actions"><button data-az-app="safezones">Safe zones</button><button data-az-app="imok">I'm OK</button></div>`,
    familydetail: () => `${subhead('FAMILY MEMBER','Mom')}<div class="family-profile"><div class="avatar large">M</div><strong>Home</strong><small>Online now · Battery 74%</small></div><div class="phone-info-grid"><div><small>LOCATION</small><strong>Home</strong></div><div><small>BATTERY</small><strong>74%</strong></div><div><small>LAST UPDATE</small><strong>Now</strong></div><div><small>SHARING</small><strong>Enabled</strong></div></div><button class="phone-wide-action">☎ Call Mom</button>`,
    battery: () => `${subhead('DEVICE STATUS',"Grandma's phone")}<div class="battery-big"><span>12%</span></div><div class="phone-warning"><strong>Low battery</strong><p>The phone is online, but battery is low. A family member can choose whether to check in.</p></div><button class="phone-wide-action" data-az-app="contacts">☎ Check in</button>`,
    safezones: () => `${subhead('FAMILY SAFETY','Safe zones')}<div class="zone-list"><div><span>⌂</span><p><strong>Home</strong><small>Active · Arrive/leave alerts</small></p><b>ON</b></div><div><span>▣</span><p><strong>School</strong><small>Active · Weekdays</small></p><b>ON</b></div><div><span>♥</span><p><strong>Grandma's house</strong><small>Optional family zone</small></p><b>ON</b></div></div><div class="privacy-mini-note">Visible and consent-based. No hidden tracking.</div>`,
    imok: () => `${subhead('CHECK-IN',"I'm OK")}<div class="ok-orb">✓</div><h4 class="phone-center-title">Let family know you're safe</h4><p class="phone-center-muted wide">Send a simple check-in without starting an emergency alert.</p><button class="phone-wide-action good" id="sendOkDemo">Send “I'm OK”</button><div id="okResult" class="ok-result">Ready to send to trusted contacts.</div>`,
    sosphone: () => `${subhead('EMERGENCY','Get help')}<div class="phone-sos-orb">SOS</div><p class="phone-center-muted wide">Choose what is happening. Trusted contacts and location sharing activate only when you confirm.</p><div class="sos-phone-grid"><button>I feel unsafe</button><button>I'm lost</button><button>Medical help</button><button>Call family</button></div><button class="phone-sos active-demo">Hold to activate SOS</button>`,
    settings: () => `${subhead('SYSTEM','Settings')}<div class="android-settings"><button data-az-app="privacysettings"><span>◉</span><b>Privacy & permissions</b><i>›</i></button><button data-az-app="connectivity"><span>⌁</span><b>Network & connectivity</b><i>›</i></button><button data-az-app="batterysettings"><span>ϟ</span><b>Battery</b><i>›</i></button><button data-az-app="deviceinfo"><span>i</span><b>About phone</b><i>›</i></button></div>`,
    privacysettings: () => `${subhead('PRIVACY','Permissions')}<div class="privacy-summary"><strong>4 permissions active</strong><small>Sensitive access stays visible and controllable.</small></div><div class="settings-toggle-list">${toggle('Microphone','Only when an app needs it')}${toggle('Camera','Only when an app needs it')}${toggle('Location','Safety and navigation')}${toggle('Family location','Trusted family only')}</div>`,
    connectivity: () => `${subhead('SETTINGS','Network & connectivity')}<div class="settings-list"><div><span>Mobile network</span><strong>5G</strong></div><div><span>Wi-Fi</span><strong>Connected</strong></div></div><div class="settings-toggle-list">${toggle('Bluetooth','Accessories')}${toggle('NFC','Contactless payments')}</div>`,
    batterysettings: () => `${subhead('SETTINGS','Battery')}<div class="battery-summary"><strong>82%</strong><span>Battery health · Good</span></div><div class="settings-toggle-list">${toggle('80% charge limit','Reduce battery wear')}${toggle('Adaptive charging','Learns your routine')}</div>`,
    deviceinfo: () => `${subhead('ABOUT','A-Z Care Phone')}<div class="settings-list"><div><span>Memory</span><strong>12 GB RAM</strong></div><div><span>Storage</span><strong>256 GB</strong></div><div><span>System</span><strong>Android</strong></div><div><span>Security</span><strong class="safe-text">Protected ✓</strong></div></div><a class="phone-link" href="hardware.html">Full hardware specifications →</a>`,
    camera: () => `${subhead('CAMERA','Camera')}<div class="camera-demo"><div class="camera-focus">+</div><small>Camera preview</small></div><div class="camera-controls"><span>▧</span><button aria-label="Take photo"></button><span>↻</span></div>`,
    browser: () => `${subhead('BROWSER','Chrome')}<div class="browser-shell"><div class="browser-toolbar"><button aria-label="Home">⌂</button><div class="browser-address"><span>⌕</span><span>Search or type web address</span></div><button aria-label="Tabs">1</button><button aria-label="Menu">⋮</button></div><div class="browser-page"><div class="browser-brand">G</div><div class="browser-search"><span>⌕</span><span>Search the web</span><b>⌁</b></div><div class="browser-shortcuts"><button><span>A</span><small>A-Z Care</small></button><button><span>W</span><small>Weather</small></button><button><span>N</span><small>News</small></button><button><span>+</span><small>Add</small></button></div><div class="browser-safety-card"><span>◇</span><div><strong>A-Z Care protection is active</strong><small>Suspicious links can be checked before you open them.</small></div></div></div><div class="browser-bottom"><button>‹</button><button>›</button><button>⌂</button><button>▢</button><button>⋮</button></div></div>`,
    health: () => `${subhead('A-Z CARE','Health')}<div class="health-intro"><strong>Everyday health, made simpler.</strong><small>Track useful information, get reminders and connect health events with trusted help.</small></div><div class="android-settings health-list"><button><span>◒</span><b>Diabetes<small>Photo food · estimate carbs & bread units · log glucose and insulin taken</small></b><i>›</i></button><button><span>◷</span><b>Medication<small>Simple schedule · Taken / Missed · reminders</small></b><i>›</i></button><button><span>♡</span><b>Blood pressure<small>Save pressure and pulse · view recent history</small></b><i>›</i></button><button><span>⌁</span><b>Fall detection<small>Possible fall → check-in countdown → alert trusted contacts if there is no response</small></b><i>›</i></button><button><span>≡</span><b>Health history<small>Food, glucose, medication, pressure and safety events in one timeline</small></b><i>›</i></button></div><div class="health-note"><strong>Concept feature</strong><small>Health tools support logging, understanding and sharing information. They do not replace medical advice or prescribe insulin doses.</small></div>`
  };

  function render(target, push = true) {
    if (target === 'androidhome' || target === 'home') return home();
    const renderer = screens[target]; if (!renderer) return;
    if (push && current !== target) history.push(current);
    current = target;
    const p = view(); if (!p) return;
    p.innerHTML = renderer(); bind();
  }
  function open(target) { render(target, true); }
  function back() { const previous = history.pop() || 'androidhome'; previous === 'androidhome' ? home() : render(previous, false); }

  function bind() {
    const p = view(); if (!p) return;
    p.querySelectorAll('[data-az-app],[data-app]').forEach(button => button.onclick = event => { event.preventDefault(); event.stopPropagation(); open(button.dataset.azApp || button.dataset.app); });
    p.querySelectorAll('[data-az-back],[data-back]').forEach(button => button.onclick = event => { event.preventDefault(); event.stopPropagation(); back(); });
    p.querySelectorAll('[data-setting-toggle]').forEach(button => button.onclick = () => button.classList.toggle('on'));
    p.querySelector('[data-az-home]')?.addEventListener('click', home);
    const sendOk = p.querySelector('#sendOkDemo');
    if (sendOk) sendOk.onclick = () => { sendOk.textContent = 'Sent ✓'; sendOk.disabled = true; const result = p.querySelector('#okResult'); if (result) { result.textContent = 'Trusted contacts received your check-in.'; result.classList.add('sent'); } };
    const sos = p.querySelector('.active-demo');
    if (sos) sos.onclick = () => { sos.textContent = 'SOS demo activated ✓'; sos.disabled = true; };
  }

  function compactLanding() {
    document.querySelector('.hero-actions .button.ghost')?.remove();
    const heroLead = document.querySelector('.hero-lead'); if (heroLead) heroLead.textContent = 'A-Z Care combines digital safety, AI assistance, family protection and simple health tools in one familiar smartphone experience.';
    const heroButton = document.querySelector('.hero-actions .button.primary'); if (heroButton) heroButton.textContent = 'Explore the phone ↓';
    document.querySelectorAll('.desktop-nav a[href="#ai"],.desktop-nav a[href="#sos"]').forEach(a => a.remove());
    document.getElementById('ai')?.remove(); document.getElementById('scam')?.remove(); document.getElementById('sos')?.remove(); document.querySelector('.cta-section')?.remove();
    const overview = document.getElementById('overview'); if (overview) overview.innerHTML = `<div class="container"><div class="compact-heading reveal"><p class="eyebrow">WHAT IT DOES</p><h2>One phone. Safety that adapts to you.</h2><p>A familiar smartphone experience with protection, family tools, AI assistance and simple health support built around everyday use.</p></div><div class="compact-grid"><article class="compact-card reveal"><div class="compact-icon">◇</div><h3>Protect</h3><p>Check messages, links and callers before acting.</p></article><article class="compact-card reveal"><div class="compact-icon">✦</div><h3>AI Care</h3><p>Explain risk simply and suggest safer next steps.</p></article><article class="compact-card reveal"><div class="compact-icon">♥</div><h3>Health</h3><p>Diabetes logging, medication, pressure and fall-detection concepts in one simple place.</p></article><article class="compact-card reveal"><div class="compact-icon">⌖</div><h3>Family & SOS</h3><p>Consent-based location, trusted contacts and emergency escalation.</p></article></div></div>`;
    const modes = document.getElementById('modes'); if (modes) modes.innerHTML = `<div class="container"><div class="compact-heading reveal"><p class="eyebrow">WHO IT'S FOR</p><h2>Different people. Different risks.</h2></div><div class="compact-grid audience-grid"><article class="compact-card reveal"><div class="compact-icon">K</div><h3>Kids</h3><p>Safer communication, location and simple protection.</p></article><article class="compact-card reveal"><div class="compact-icon">S</div><h3>Seniors</h3><p>Clear warnings, trusted contacts, health support and simple emergency actions.</p></article><article class="compact-card reveal"><div class="compact-icon">F</div><h3>Families</h3><p>Consent-based safety tools without hidden tracking.</p></article></div></div>`;
    const privacy = document.getElementById('privacy'); if (privacy) privacy.innerHTML = `<div class="container"><div class="compact-heading reveal"><p class="eyebrow">PRIVACY</p><h2>Safety without surveillance.</h2></div><div class="principles"><div class="principle"><strong>Visible controls</strong><span>Permissions stay understandable and controllable.</span></div><div class="principle"><strong>Consent first</strong><span>Family sharing is explicit, not hidden.</span></div><div class="principle"><strong>Minimum necessary data</strong><span>Use only what a safety feature actually needs.</span></div></div></div>`;
    const roadmap = document.getElementById('roadmap'); if (roadmap) roadmap.innerHTML = `<div class="container"><div class="compact-heading reveal"><p class="eyebrow">ROADMAP</p><h2>Concept → Prototype → Testing</h2></div><div class="roadmap-short"><div><small>01</small><strong>Concept</strong><span>Product direction and interactive experience.</span></div><div><small>02</small><strong>Prototype</strong><span>Android flows and hardware platform.</span></div><div><small>03</small><strong>Testing</strong><span>Real users, safety validation and iteration.</span></div></div></div>`;
    document.getElementById('survey')?.classList.add('compact-section');
  }

  function initNavigation() {
    const nav = document.querySelector('.nav'); if (!nav || nav.querySelector('.mobile-menu-button')) return;
    const button = document.createElement('button'); button.className = 'mobile-menu-button'; button.type = 'button'; button.setAttribute('aria-label','Open navigation'); button.setAttribute('aria-expanded','false'); button.textContent = '☰'; nav.appendChild(button);
    const menu = document.createElement('nav'); menu.className = 'mobile-menu'; menu.setAttribute('aria-label','Mobile navigation'); menu.innerHTML = '<a href="#product">Product</a><a href="#family">Family</a><a href="#modes">Kids & Seniors</a><a href="#privacy">Privacy</a><a href="#roadmap">Roadmap</a>'; document.body.appendChild(menu);
    const close = () => { menu.classList.remove('open'); document.body.classList.remove('mobile-menu-open'); button.setAttribute('aria-expanded','false'); button.textContent='☰'; };
    button.onclick = () => { const opening = !menu.classList.contains('open'); menu.classList.toggle('open', opening); document.body.classList.toggle('mobile-menu-open', opening); button.setAttribute('aria-expanded', String(opening)); button.textContent = opening ? '×' : '☰'; };
    menu.querySelectorAll('a').forEach(link => link.addEventListener('click', close)); window.addEventListener('resize', () => { if (window.innerWidth > 640) close(); });
  }

  function init() {
    compactLanding(); initNavigation(); document.querySelectorAll('.phone-nav').forEach(node => node.remove()); home();
    document.querySelectorAll('[data-phone-screen]').forEach(button => button.addEventListener('click', () => { open(button.dataset.phoneScreen); document.getElementById('product')?.scrollIntoView({behavior:'smooth', block:'center'}); }));
    document.querySelectorAll('[data-scroll]').forEach(button => button.addEventListener('click', () => document.querySelector(button.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
    if ('IntersectionObserver' in window) { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), {threshold:.12}); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); }
    setInterval(tick, 30000); window.addEventListener('pageshow', tick); document.addEventListener('visibilitychange', () => { if (!document.hidden) tick(); });
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, {once:true}); else init();
})();